name: WaterProof
main: net.drgnome.waterproof.WPlugin
version: #VERSION#
author: Siguza
load: STARTUP
depend: [NBTLib]
commands:
    waterproof:
        description: Shows the version of WaterProof
        permissions: waterproof.all
        usage: /waterproof
permissions:
    waterproof.all:
        decsription: Notifies you of new WaterProof versions and allows you to use the /waterproof command